export const data = [
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Inactive',
  },
  {
    customerName: 'Floyd Miles',
    company: 'Adobe',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Ronald Richards',
    company: 'Tesla',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Inactive',
  },
  {
    customerName: 'Marvin McKinney',
    company: 'Google',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jerome Bell',
    company: 'Yahoo',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Kristin Watson',
    company: 'Facebook',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Inactive',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'lslslsl',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
  {
    customerName: 'Jane Cooper',
    company: 'Microsoft',
    phoneNumber: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    status: 'Active',
  },
];
